In [4]:
import pandas as pd
import folium
from haversine import haversine

In [5]:
import json

with open('responses.json') as f:
    d = json.load(f)

with open('responses2.json') as f2:
    d2 = json.load(f2)

In [6]:
valid = [item for item in d if "scenarioInformation" in item]
valid2 = [item for item in d2 if "scenarioInformation" in item]

In [7]:
def load_in(path):
    with open(path) as f:
        d = json.load(f)
    valid = [item for item in d if "scenarioInformation" in item]
    partial = []
    for item in valid:
        for sub_connection in item["connections"]:
            partial.extend(sub_connection["transportplanElements"])
    normalized_data = pd.json_normalize(partial)
    df = pd.DataFrame(normalized_data)
    reduced = df[["fromInfrastructureLocation.name" , 
              "fromInfrastructureLocation.latitude" ,
              "fromInfrastructureLocation.longitude", 
              "toInfrastructureLocation.name" ,
              "toInfrastructureLocation.latitude", 
              "toInfrastructureLocation.longitude", 
              ]]
    no_dup = reduced.drop_duplicates(["fromInfrastructureLocation.name" , "toInfrastructureLocation.name"]).reset_index(drop="index")
    return no_dup
    
df1 = load_in("responses.json")
df2 = load_in("responses2.json")

maschen = load_in("maschen_departure5.json")

In [8]:


with open("maschen_departure5.json") as f:
    d = json.load(f)
partial = []
item = d[0]
for sub_connection in item["connections"]:
    partial.extend(sub_connection["transportplanElements"])
normalized_data = pd.json_normalize(partial)
df = pd.DataFrame(normalized_data)
reduced = df[["fromInfrastructureLocation.name" , 
            "fromInfrastructureLocation.latitude" ,
            "fromInfrastructureLocation.longitude", 
            "toInfrastructureLocation.name" ,
            "toInfrastructureLocation.latitude", 
            "toInfrastructureLocation.longitude", 
            ]]
no_dup = reduced.drop_duplicates().reset_index(drop="index")

In [9]:
df

,blockName,compositionEndWeekdays,compositionEndTimeOfDay,departureWeekdays,departureTimeOfDay,arrivalWeekdays,arrivalTimeOfDay,decompositionEndWeekdays,decompositionEndTimeOfDay,runDuration,...,toInfrastructureLocation.countryNumber,toInfrastructureLocation.locationNumber,toInfrastructureLocation.freightCarLocationNumber,toInfrastructureLocation.name,toInfrastructureLocation.latitude,toInfrastructureLocation.longitude,toInfrastructureLocation.objectKeyAlpha,toInfrastructureLocation.objectKeySequence,toInfrastructureLocation.tafTsiPrimaryCode,toInfrastructureLocation.tafTsiSubsidiaryType
0,AM.9999-AM O-1-N708,"[Monday, Wednesday]",28800,"[Monday, Wednesday]",36900,"[Monday, Wednesday]",37800,"[Monday, Wednesday]",37800,9000,...,80,011767,None,Maschen Rbf (Mnof),53.408774,10.052296,MASCHEN RBF S/N,1,16858,None
1,AM O-AIZ-53527-1,"[Monday, Wednesday]",-16200,"[Tuesday, Thursday]",84960,"[Wednesday, Friday]",5640,"[Wednesday, Friday]",92640,108840,...,80,014951,None,Itzehoe,53.923981,9.510444,ITZEHOE,1,15253,None
2,AIZ-ABK-53507-3[EV],"[Wednesday, Friday]",23580,"[Wednesday, Friday]",24180,"[Wednesday, Friday]",26820,"[Wednesday, Friday]",27420,3840,...,80,015024,None,Brunsbüttel,53.898383,9.159850,BRUNSBüTTEL,1,11760,None
3,ABK-AKUD.0004-53510-1,"[Wednesday, Friday]",28800,"[Wednesday, Friday]",30240,"[Wednesday, Friday]",30780,"[Wednesday, Friday]",31680,2880,...,80,010066,None,Kudensee,53.920346,9.218534,KUDENSEE,1,15939,None
4,AM.9999-AM O-1-N716,"[Monday, Wednesday]",48600,"[Monday, Wednesday]",55500,"[Monday, Wednesday]",55800,"[Monday, Wednesday]",67200,18600,...,80,011767,None,Maschen Rbf (Mnof),53.408774,10.052296,MASCHEN RBF S/N,1,16858,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,ABK-AKUD.0004-53514-1,[Tuesday],28200,[Tuesday],30240,[Tuesday],30780,[Tuesday],31680,3480,...,80,010066,None,Kudensee,53.920346,9.218534,KUDENSEE,1,15939,None
256,AM.9999-AM O-1-N732,[Sunday],73200,[Sunday],76200,[Sunday],76500,[Sunday],79620,6420,...,80,011767,None,Maschen Rbf (Mnof),53.408774,10.052296,MASCHEN RBF S/N,1,16858,None
257,AM O-AIZ-50664-1,[Monday],16200,[Monday],27840,[Monday],34320,[Monday],34920,18720,...,80,014951,None,Itzehoe,53.923981,9.510444,ITZEHOE,1,15253,None
258,AIZ-ABK-53507-3[EV],[Tuesday],23580,[Tuesday],24180,[Tuesday],26820,[Tuesday],27420,3840,...,80,015024,None,Brunsbüttel,53.898383,9.159850,BRUNSBüTTEL,1,11760,None
259,ABK-AKUD.0004-53514-1,[Tuesday],28200,[Tuesday],30240,[Tuesday],30780,[Tuesday],31680,3480,...,80,010066,None,Kudensee,53.920346,9.218534,KUDENSEE,1,15939,None

In [10]:
df

,blockName,compositionEndWeekdays,compositionEndTimeOfDay,departureWeekdays,departureTimeOfDay,arrivalWeekdays,arrivalTimeOfDay,decompositionEndWeekdays,decompositionEndTimeOfDay,runDuration,...,toInfrastructureLocation.countryNumber,toInfrastructureLocation.locationNumber,toInfrastructureLocation.freightCarLocationNumber,toInfrastructureLocation.name,toInfrastructureLocation.latitude,toInfrastructureLocation.longitude,toInfrastructureLocation.objectKeyAlpha,toInfrastructureLocation.objectKeySequence,toInfrastructureLocation.tafTsiPrimaryCode,toInfrastructureLocation.tafTsiSubsidiaryType
0,AM.9999-AM O-1-N708,"[Monday, Wednesday]",28800,"[Monday, Wednesday]",36900,"[Monday, Wednesday]",37800,"[Monday, Wednesday]",37800,9000,...,80,011767,None,Maschen Rbf (Mnof),53.408774,10.052296,MASCHEN RBF S/N,1,16858,None
1,AM O-AIZ-53527-1,"[Monday, Wednesday]",-16200,"[Tuesday, Thursday]",84960,"[Wednesday, Friday]",5640,"[Wednesday, Friday]",92640,108840,...,80,014951,None,Itzehoe,53.923981,9.510444,ITZEHOE,1,15253,None
2,AIZ-ABK-53507-3[EV],"[Wednesday, Friday]",23580,"[Wednesday, Friday]",24180,"[Wednesday, Friday]",26820,"[Wednesday, Friday]",27420,3840,...,80,015024,None,Brunsbüttel,53.898383,9.159850,BRUNSBüTTEL,1,11760,None
3,ABK-AKUD.0004-53510-1,"[Wednesday, Friday]",28800,"[Wednesday, Friday]",30240,"[Wednesday, Friday]",30780,"[Wednesday, Friday]",31680,2880,...,80,010066,None,Kudensee,53.920346,9.218534,KUDENSEE,1,15939,None
4,AM.9999-AM O-1-N716,"[Monday, Wednesday]",48600,"[Monday, Wednesday]",55500,"[Monday, Wednesday]",55800,"[Monday, Wednesday]",67200,18600,...,80,011767,None,Maschen Rbf (Mnof),53.408774,10.052296,MASCHEN RBF S/N,1,16858,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
255,ABK-AKUD.0004-53514-1,[Tuesday],28200,[Tuesday],30240,[Tuesday],30780,[Tuesday],31680,3480,...,80,010066,None,Kudensee,53.920346,9.218534,KUDENSEE,1,15939,None
256,AM.9999-AM O-1-N732,[Sunday],73200,[Sunday],76200,[Sunday],76500,[Sunday],79620,6420,...,80,011767,None,Maschen Rbf (Mnof),53.408774,10.052296,MASCHEN RBF S/N,1,16858,None
257,AM O-AIZ-50664-1,[Monday],16200,[Monday],27840,[Monday],34320,[Monday],34920,18720,...,80,014951,None,Itzehoe,53.923981,9.510444,ITZEHOE,1,15253,None
258,AIZ-ABK-53507-3[EV],[Tuesday],23580,[Tuesday],24180,[Tuesday],26820,[Tuesday],27420,3840,...,80,015024,None,Brunsbüttel,53.898383,9.159850,BRUNSBüTTEL,1,11760,None
259,ABK-AKUD.0004-53514-1,[Tuesday],28200,[Tuesday],30240,[Tuesday],30780,[Tuesday],31680,3480,...,80,010066,None,Kudensee,53.920346,9.218534,KUDENSEE,1,15939,None

In [11]:
maschen

,fromInfrastructureLocation.name,fromInfrastructureLocation.latitude,fromInfrastructureLocation.longitude,toInfrastructureLocation.name,toInfrastructureLocation.latitude,toInfrastructureLocation.longitude
0,MASCHEN RBF,53.398500,10.059800,Maschen Rbf (Mnof),53.408774,10.052296
1,Maschen Rbf (Mnof),53.408774,10.052296,Itzehoe,53.923981,9.510444
2,Itzehoe,53.923981,9.510444,Brunsbüttel,53.898383,9.159850
3,Brunsbüttel,53.898383,9.159850,Kudensee,53.920346,9.218534
4,Maschen Rbf (Mnof),53.408774,10.052296,Lüneburg,53.250440,10.419914
...,...,...,...,...,...,...
638,DUISBURG-HOCHFELD S,51.408789,6.754565,Duisburg-Wanheim,51.389938,6.749258
639,Mannheim Rbf,49.459657,8.510961,Kehl,48.578590,7.814428
640,Landshut (Bay) Hbf,48.547560,12.135851,Dingolfing,48.641622,12.487640
641,Dingolfing,48.641622,12.487640,Dingolfing PA Scholz,48.641402,12.468090
642,Krefeld-Linn,51.338277,6.630361,Krefeld Kriba,51.329115,6.604827

In [12]:
# df2.columns = ["toInfrastructureLocation.name" ,
#               "toInfrastructureLocation.latitude", 
#               "toInfrastructureLocation.longitude", 
#               "fromInfrastructureLocation.name" , 
#               "fromInfrastructureLocation.latitude" ,
#               "fromInfrastructureLocation.longitude"
#               ]

In [13]:
df2

,fromInfrastructureLocation.name,fromInfrastructureLocation.latitude,fromInfrastructureLocation.longitude,toInfrastructureLocation.name,toInfrastructureLocation.latitude,toInfrastructureLocation.longitude
0,Kudensee,53.920346,9.218534,Itzehoe,53.923981,9.510444
1,Itzehoe,53.923981,9.510444,MASCHEN RBF,53.398500,10.059800
2,MASCHEN RBF,53.398500,10.059800,Maschen Rbf (Mnof),53.408774,10.052296
3,Maschen Rbf (Mnof),53.408774,10.052296,Seddin,52.291505,12.984401
4,Seddin,52.291505,12.984401,Halle (Saale) Gbf,51.483539,11.986633
...,...,...,...,...,...,...
659,Großen Buseck Industriestammgleis,50.598781,8.801221,Wetzlar,50.565703,8.503967
660,Ludwigsfelde,52.299155,13.267600,Seddin,52.291505,12.984401
661,Duisburg-Wanheim,51.389938,6.749258,DUISBURG-HOCHFELD S,51.408789,6.754565
662,Dingolfing PA Scholz,48.641402,12.468090,Dingolfing,48.641622,12.487640
663,Krefeld Kriba,51.329115,6.604827,Krefeld-Linn,51.338277,6.630361

In [14]:
combined = pd.concat([df1,df2,maschen]).reset_index(drop = True)
combined = combined.drop_duplicates(["fromInfrastructureLocation.name" , "toInfrastructureLocation.name"])

In [15]:
combined["distance"] = combined.apply(
    lambda row: haversine(
        (row["toInfrastructureLocation.latitude"], row["toInfrastructureLocation.longitude"]),
        (row["fromInfrastructureLocation.latitude"], row["fromInfrastructureLocation.longitude"])
    ),
    axis=1
)

In [16]:
combined

,fromInfrastructureLocation.name,fromInfrastructureLocation.latitude,fromInfrastructureLocation.longitude,toInfrastructureLocation.name,toInfrastructureLocation.latitude,toInfrastructureLocation.longitude,distance
0,Leipzig-Wahren,51.380421,12.322542,Halle (Saale) Gbf,51.483539,11.986633,25.956372
1,Halle (Saale) Gbf,51.483539,11.986633,Seddin,52.291505,12.984401,112.960867
2,Seddin,52.291505,12.984401,Maschen Rbf (Mnof),53.408774,10.052296,232.783866
3,Maschen Rbf (Mnof),53.408774,10.052296,Lüneburg,53.250440,10.419914,30.098671
4,Maschen Rbf (Mnof),53.408774,10.052296,Meckelfeld,53.421844,10.033265,1.924289
...,...,...,...,...,...,...,...
1821,Braunschweig Rbf,52.249093,10.552759,Braunschweig-Rühme,52.296078,10.525867,5.535649
1822,Osnabrück Rbf Oro,52.266987,8.102419,Emden Hbf Volkswagenwerk,53.356541,7.151103,136.986599
1850,Landshut (Bay) Hbf,48.547560,12.135851,Dingolfing,48.641622,12.487640,27.905647
1851,Dingolfing,48.641622,12.487640,Dingolfing PA Scholz,48.641402,12.468090,1.436628
1852,Krefeld-Linn,51.338277,6.630361,Krefeld Kriba,51.329115,6.604827,2.045650

In [17]:
h = combined.value_counts("toInfrastructureLocation.name")

In [18]:
h

toInfrastructureLocation.name
Seelze Mitte         25
NUERNBERG RBF        21
GREMBERG             19
Seddin               19
Halle (Saale) Gbf    18
                     ..
Königsborn            1
Köln-Mülheim          1
Köln-Deutz Hafen      1
Köln-Bickendorf       1
Chemnitz Hbf          1
Name: count, Length: 642, dtype: int64

In [19]:
import plotly.express as px

In [20]:
px.histogram(combined,x = "distance",cumulative=True)

In [21]:
m = folium.Map(location=[50, 10], zoom_start=6)
cities = set()
for _, row in combined.iterrows():
    # Linie zwischen Start- und Zielstation zeichnen
    folium.PolyLine([(row["fromInfrastructureLocation.latitude"], row["fromInfrastructureLocation.longitude"]),
                     (row["toInfrastructureLocation.latitude"], row["toInfrastructureLocation.longitude"])],
                    color="blue", weight=2.5).add_to(m)

    # Start-Station als Marker mit Tooltip
    folium.Marker(
        location=[row["fromInfrastructureLocation.latitude"], row["fromInfrastructureLocation.longitude"]],
        tooltip=row["fromInfrastructureLocation.name"],
        icon=folium.Icon(color="green")
    ).add_to(m)

    # End-Station als Marker mit Tooltip
    folium.Marker(
        location=[row["toInfrastructureLocation.latitude"], row["toInfrastructureLocation.longitude"]],
        tooltip=row["toInfrastructureLocation.name"],
        icon=folium.Icon(color="red")
    ).add_to(m)

# Karte anzeigen
m

In [22]:
max_dis = 0
import math
name = ()
for _, row in reduced.iterrows():
    d = math.dist([row["toInfrastructureLocation.latitude"], row["toInfrastructureLocation.longitude"]] , [row["fromInfrastructureLocation.latitude"], row["fromInfrastructureLocation.longitude"]])
    if d > max_dis:
        max_dis = d
        name = (row["fromInfrastructureLocation.name"] , row["toInfrastructureLocation.name"])

In [23]:
name

('Maschen Rbf (Mnof)', 'Itzehoe')

In [24]:
no_dup

,fromInfrastructureLocation.name,fromInfrastructureLocation.latitude,fromInfrastructureLocation.longitude,toInfrastructureLocation.name,toInfrastructureLocation.latitude,toInfrastructureLocation.longitude
0,MASCHEN RBF,53.398500,10.059800,Maschen Rbf (Mnof),53.408774,10.052296
1,Maschen Rbf (Mnof),53.408774,10.052296,Itzehoe,53.923981,9.510444
2,Itzehoe,53.923981,9.510444,Brunsbüttel,53.898383,9.159850
3,Brunsbüttel,53.898383,9.159850,Kudensee,53.920346,9.218534

In [25]:
df.columns

Index(['blockName', 'compositionEndWeekdays', 'compositionEndTimeOfDay',
       'departureWeekdays', 'departureTimeOfDay', 'arrivalWeekdays',
       'arrivalTimeOfDay', 'decompositionEndWeekdays',
       'decompositionEndTimeOfDay', 'runDuration', 'runLength',
       'trainsetLength', 'trainsetWeight', 'maxVelocity', 'trainNumber',
       'combinedTrafficCoding', 'linkClass', 'trainCategory',
       'fromInfrastructureLocation.code',
       'fromInfrastructureLocation.countryNumber',
       'fromInfrastructureLocation.locationNumber',
       'fromInfrastructureLocation.freightCarLocationNumber',
       'fromInfrastructureLocation.name',
       'fromInfrastructureLocation.latitude',
       'fromInfrastructureLocation.longitude',
       'fromInfrastructureLocation.objectKeyAlpha',
       'fromInfrastructureLocation.objectKeySequence',
       'fromInfrastructureLocation.tafTsiPrimaryCode',
       'fromInfrastructureLocation.tafTsiSubsidiaryType',
       'toInfrastructureLocation.code',
       'toInfrastructureLocation.countryNumber',
       'toInfrastructureLocation.locationNumber',
       'toInfrastructureLocation.freightCarLocationNumber',
       'toInfrastructureLocation.name', 'toInfrastructureLocation.latitude',
       'toInfrastructureLocation.longitude',
       'toInfrastructureLocation.objectKeyAlpha',
       'toInfrastructureLocation.objectKeySequence',
       'toInfrastructureLocation.tafTsiPrimaryCode',
       'toInfrastructureLocation.tafTsiSubsidiaryType'],
      dtype='object')

In [26]:
with open("test.json", "w") as f:
    f.write(json.dumps(test))

NameError: name 'test' is not defined

In [ ]:
l = df["transportplanElements"]

KeyError: 'transportplanElements'

In [ ]:
for i in l:
    if len(i) > 1:
        print(len(i))

4
4
4
6
6
4
4
5
5
6
6
5
5
5
5
4
4
4
3
5
5
4
5
5
5
5
4
4
5
5
5
5
5
5
5
5
4
4
5
5
4
4
2
3
3
4
4
6
6
6
6
4
4
4
4
4
4
4
4
4
4
5
4
4
4
4
5
4
6
5
6
6
6
6
5
5
5
5
5
5
4
4
4
4
3
3
3
3
4
4
4
4
3
3
4
4
3
3
4
4
4
4
6
5
5
4
4
4
4
5
5
3
3
3
3
4
4
5
5
5
5
3
3
4
4
4
4
5
5
4
4
5
5
5
5
4
4
5
5
5
5
5
5
4
4
5
5
5
5
5
5
6
6
5
5
5
5
3
6
6
5
5
5
5
6
6
5
5
5
5
5
5
4
4
6
6
4
4
4
4
4
4
4
4
5
5
4
4
5
5
6
6
7
7
4
4
4
4
4
4
4
4
6
6
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
4
3
3
4
4
3
3
3
3
3
6
6
4
4
4
4
5
5
2
3
5
5
5
5
4
4
4
4
5
5
3
3
5
5
4
4
3
3
3
3
3
3
4
4
3
3
3
3
3
4
4
3
3
5
5
2
5
5
7
7
3
3
3
3
3
3
3
3
3
3
3
5
5
5
5
5
5
5
5
4
4
4
4
4
4
6
6
3
3
5
5
6
6
5
5
7
7
3
3
4
4
5
5
5
4
4
6
6
5
5
5
5
3
5
5
5
5
5
5
5
5
4
4
3
3
5
5
3
4
4
4
4
6
6
3
3
5
5
5
5
4
4
4
4
4
3
3
3
3
4
4
3
3
3
3
4
4
4
4
3
3
4
4
5
5
5
5
6
6
2
3
3
2
2
2
3
4
4
3
3
4
4
4
4
2
4
4
4
4
5
4
5
5
5
5
5
5
4
4
4
4
3
3
4
4
5
5
5
5
3
4
4
4
4
4
4
4
4
3
4
4
4
4
4
4
4
4
5
4
5
5
5
5
4
5
5
4
4
6
6
4
4
4
4
4
4
5
5
4
5
5
4
3
3
4
4
5
5
5
5
4
4
4
4
4
4
5
5
5
5
5
5
6
6
6
5
5
7
7
5
5
5
5
5
5
5
5
5
5
5
5
5
5
2
6
6
3
6
4
4
5
5
5
5
4
4
5
4
4
4
4
6
6
6
6
5
5
5
5
4
4
2
6
6
5
5
5
5
3
3
5
4
4
6
6
5
5
4
4
3
5
5
5
5
5
5
5
5
6
6
5
5
6
6
7
7
5
5
5
5
5
5
4
4
5
5
5
5
5
5
3
3
3
3
4
5
5
4
4
4
4
4
4
4
4
4
5
5
5
5
4
4
5
5
4
4
6
5
5
5
6
6
5
5
4
4
3
3
4
4
5
4
4
4
5
5
3
4
4
3
3
4
4
2
3
3
4
4
4
4
7
5
5
4
4
3
5
5
6
6
6
7
7
4
8
8
6
6
3
3
3
3
4
4
4
4
5
5
4
4
5
5
5
5
5
5
3
3
4
4
5
5
4
4
4
4
4
4
4
4
4
4
4
4
6
6
6
5
5
5
5
4
4
4
4
4
4
7
7
7
7
4
4
5
3
5
5
3
2
4
4
5
5
5
5
4
6
6
3
5
5
4
4
5
5
4
4
3
5
5
4
4
3
3
3
3
6
6
4
4
4
5
5
3
4
5
4
4
5
5
4
3
4
4
5
5
4
4
6
5
2
4
4
4
4
3
4
4
4
4
4
4
3
3
5
5
6
6
5
5
6
5
5
5
4
4
3
3
3
4
4
5
5
5
4
4
4
4
4
6
6
3
4
4
6
6
3
4
4

In [ ]:
len(connections)

828

In [ ]:
for item in d:
    print("scenarioInformation" in item)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
False
True
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False
False
True
True
False
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
False
True
False
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
False
True
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
False
True
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
False
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
False
True
False
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False
False
False
True
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
True
False
True
False
True
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
False
True
False
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
True
False
True
False
True
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
False
True
False
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
True
False
True
False
True
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False
False
True
False
True
False
False
False
False
False
False
False
False
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
False
True
True
True
False